In [3]:
import torch 
import numpy as np

In [4]:
data = [[1,2],[3,4]] #2*2
x_data = torch.tensor(data)

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0396, 0.9287],
        [0.7781, 0.2594]]) 



In [11]:
shape = (2,3) 
rand_tensor = torch.rand(shape) 
ones_tensor = torch.ones(shape)
print(rand_tensor) 
print(ones_tensor)

tensor([[0.8979, 0.2374, 0.3086],
        [0.8673, 0.9272, 0.0730]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
print(rand_tensor.dtype) 
print(rand_tensor.device)

torch.float32
cpu


In [16]:
tensor = rand_tensor
if torch.accelerator.is_available():
	tensor = tensor.to(torch.accelerator.current_accelerator())

In [17]:
tensor.device

device(type='cuda', index=0)

In [20]:
print(torch.cat([tensor,tensor,tensor],dim=1))

tensor([[0.8979, 0.2374, 0.3086, 0.8979, 0.2374, 0.3086, 0.8979, 0.2374, 0.3086],
        [0.8673, 0.9272, 0.0730, 0.8673, 0.9272, 0.0730, 0.8673, 0.9272, 0.0730]],
       device='cuda:0')


In [21]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.8062, 0.0563, 0.0953],
        [0.7522, 0.8597, 0.0053]], device='cuda:0')

In [22]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

3.3115038871765137 <class 'float'>
